# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
sitename: TBOOX 
title: TBOOX Open Source Project
title-cn: TBOOX开源工程
description: Focus on cross-platform development using c language
description-cn: 专注于跨平台c开发解决方案
keywords: tbox,xmake,gbox,cross-platform,c,lua,build,makefile,make,compile,linux,programing
keywords-cn: tbox,xmake,gbox,c,lua,跨平台,构建工具,编译工具,makefile,make,编译器,图形库,linux,编程,开发
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.tboox.org" # the base hostname & protocol for your site
domain: "tboox.org"

permalink: /:year/:month/:day/:title/

# other links
twitter_username: waruqi
facebook_username: waruqi
github_username:  waruqi
email: waruqi@gmail.com
weibo_username: 
zhihu_username: waruqi
linkedIn_username: 
dribbble_username: 

# description footer
description_footer: Copyright (c) 2016-2017 tboox.org

# comments
changyan_appid: cysUk4sMC
changyan_appkey: prod_a1ee57b8c7df5085908e9e798786ee03
disqus_shortname: zh-tboox

# statistic analysis 
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
baidu_tongji_id: 162f1cd478898a0686b0b5d5115e2af2
google_analytics_id: 

# ads
#adsbygoogle_client: ca-pub-5219622969547045
#adsbygoogle_slot: 2494302416
amazon_ads_cn: tboox01-23
#amazon_ads_en: tboox-20
#chitika_ads_en: waruqi
#chitika_ads_color_button: ebd9eb
#chitika_ads_color_button_text: 473047
#baiduads_slide_id0: u2755106 # pc slide
baiduads_slide_id1: u2872323 # pc flat
#baiduads_slide_id2: u2777570 # mobile flat

# markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# gems
gems:               ['jekyll-paginate', 'jekyll-multiple-languages']

# multiple-languages
languages:          ['en', 'cn']
language_default:   'en'

# paginate
paginate: 5

